image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

install:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &

build: off

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true
